#!/bin/bash

cat Pruebas/01_PruebaMatriz2MatricesChicasPrimeraSinErrorSegundaConError    |./tp0
cat Pruebas/02_PruebaMatriz2MatricesGrandesPrimeraConErrorSegundaSinError    |./tp0
cat Pruebas/03_PruebaMatriz2MatricesGrandesPrimeraSinErrorSegundaConError    |./tp0
cat Pruebas/04_PruebaMatrizChicaProductoPorIdentidad    |./tp0
cat Pruebas/05_PruebaMatrizChicaProductoPorMatrizNula    |./tp0
cat Pruebas/06_PruebaMatrizDim1ElementoNoNumerico    |./tp0
cat Pruebas/07_PruebaMatrizDim2ElementoNoNumerico    |./tp0
cat Pruebas/08_PruebaMatrizDimChicaMuchasLineas    |./tp0
cat Pruebas/09_PruebaMatrizDimEs0    |./tp0
cat Pruebas/10_PruebaMatrizDimEsNegativa    |./tp0
cat Pruebas/11_PruebaMatrizDimMayorACantidadDeElementos    |./tp0
cat Pruebas/12_PruebaMatrizDimNoEnteroEsFloat    |./tp0
cat Pruebas/13_PruebaMatrizDimNoEnteroEsString    |./tp0
cat Pruebas/14_PruebaMatrizGrandeDim5DimEsCero    |./tp0
cat Pruebas/15_PruebaMatrizGrandeDim5DimEsNegativa    |./tp0
cat Pruebas/16_PruebaMatrizGrandeDim5DimNoEnteroEsFloat    |./tp0
cat Pruebas/17_PruebaMatrizGrandeDim5DimNoEnteroEsString    |./tp0
cat Pruebas/18_PruebaMatrizGrandeDim5ElementoNoNumerico    |./tp0
cat Pruebas/19_PruebaMatrizGrandeDim5MayorCantidadDeElementos    |./tp0
cat Pruebas/20_PruebaMatrizGrandeDim5MenorCantidadDeElementos    |./tp0
cat Pruebas/21_PruebaMatrizGrandeProductoPorIdentidad    |./tp0
cat Pruebas/22_PruebaMatrizGrandeProductoPorMatrizNula    |./tp0
cat Pruebas/23_PruebaMatrizGrandeVariasLineas    |./tp0
cat Pruebas/24_PruebaMatrizChicaProductoPorInversa    |./tp0
cat Pruebas/25_PruebaMatrizGrandeProductoPorInversa    |./tp0
cat Pruebas/26_exampleCatedra    |./tp0

